# SPDX-License-Identifier: GPL-2.0

# example:
# obj-y += XXXX.o <- object file to generate
# FILE_XXXX.o := YYYY.html <- actual html file to be embedded
# FSPATH_XXXX.o := ZZZ/WWW.EXT <- virtual fs path to be used inside u-boot

obj-y += 404.o
FILE_404.o := .min/404.html
FSPATH_404.o := 404.html

obj-$(CONFIG_WEBUI_FAILSAFE_BACKUP) += backup.o
FILE_backup.o := .min/backup.html
FSPATH_backup.o := backup.html

obj-y += bl2.o
FILE_bl2.o := .min/bl2.html
FSPATH_bl2.o := bl2.html

obj-y += booting.o
FILE_booting.o := .min/booting.html
FSPATH_booting.o := booting.html

obj-$(CONFIG_WEBUI_FAILSAFE_CONSOLE) += console.o
FILE_console.o := .min/console.html
FSPATH_console.o := console.html

obj-$(CONFIG_WEBUI_FAILSAFE_ENV) += env.o
FILE_env.o := .min/env.html
FSPATH_env.o := env.html

obj-$(CONFIG_WEBUI_FAILSAFE_FACTORY) += factory.o
FILE_factory.o := .min/factory.html
FSPATH_factory.o := factory.html

obj-y += fail.o
FILE_fail.o := .min/fail.html
FSPATH_fail.o := fail.html

obj-$(CONFIG_WEBUI_FAILSAFE_FLASH) += flash.o
FILE_flash.o := .min/flash.html
FSPATH_flash.o := flash.html

obj-y += flashing.o
FILE_flashing.o := .min/flashing.html
FSPATH_flashing.o := flashing.html

obj-y += gpt.o
FILE_gpt.o := .min/gpt.html
FSPATH_gpt.o := gpt.html

obj-y += index.o
FILE_index.o := .min/index.html
FSPATH_index.o := index.html

obj-y += initramfs.o
FILE_initramfs.o := .min/initramfs.html
FSPATH_initramfs.o := initramfs.html

obj-y += reboot.o
FILE_reboot.o := .min/reboot.html
FSPATH_reboot.o := reboot.html

obj-$(CONFIG_WEBUI_FAILSAFE_ENV) += settings.o
FILE_settings.o := .min/settings.html
FSPATH_settings.o := settings.html

obj-$(CONFIG_WEBUI_FAILSAFE_SIMG) += simg.o
FILE_simg.o := .min/simg.html
FSPATH_simg.o := simg.html

obj-y += uboot.o
FILE_uboot.o := .min/uboot.html
FSPATH_uboot.o := uboot.html

obj-y += favicon.o
FILE_favicon.o := favicon.svg
FSPATH_favicon.o := favicon.svg

obj-y += style.o
FILE_style.o := .min/style.css
FSPATH_style.o := style.css

obj-$(CONFIG_WEBUI_FAILSAFE_BACKUP) += backup_js.o
FILE_backup_js.o := .min/backup_js.js
FSPATH_backup_js.o := backup_js.js

obj-$(CONFIG_WEBUI_FAILSAFE_CONSOLE) += console_js.o
FILE_console_js.o := .min/console_js.js
FSPATH_console_js.o := console_js.js

obj-$(CONFIG_WEBUI_FAILSAFE_ENV) += env_js.o
FILE_env_js.o := .min/env_js.js
FSPATH_env_js.o := env_js.js

obj-$(CONFIG_WEBUI_FAILSAFE_FLASH) += flash_js.o
FILE_flash_js.o := .min/flash_js.js
FSPATH_flash_js.o := flash_js.js

obj-$(CONFIG_WEBUI_FAILSAFE_I18N) += i18n.o
FILE_i18n.o := .min/i18n.js
FSPATH_i18n.o := i18n.js

obj-y += main.o
FILE_main.o := .min/main.js
FSPATH_main.o := main.js

obj-$(CONFIG_WEBUI_FAILSAFE_ENV) += settings_js.o
FILE_settings_js.o := .min/settings_js.js
FSPATH_settings_js.o := settings_js.js

obj-y += theme.o
FILE_theme.o := .min/theme.js
FSPATH_theme.o := theme.js

# customized build rules
strip_path = $(subst /,_,$(subst -,_,$(subst .,_,$(1))))
WEBUI_FAILSAFE_JS_MINIFY_SCRIPT = $(srctree)/$(src)/../minify-js.cjs

WEBUI_FAILSAFE_CSS_MINIFY_SCRIPT = $(srctree)/$(src)/../minify-css.cjs
WEBUI_FAILSAFE_HTML_MINIFY_SCRIPT = $(srctree)/$(src)/../minify-html.cjs

quiet_cmd_minify_css = CLEANCSS $@
cmd_minify_css = mkdir -p $(dir $@) && node $(WEBUI_FAILSAFE_CSS_MINIFY_SCRIPT) $< $@

quiet_cmd_minify_html = HTMLMIN $@
cmd_minify_html = mkdir -p $(dir $@) && node $(WEBUI_FAILSAFE_HTML_MINIFY_SCRIPT) $< $@

quiet_cmd_minify_js = UGLIFY  $@
cmd_minify_js = mkdir -p $(dir $@) && node $(WEBUI_FAILSAFE_JS_MINIFY_SCRIPT) $< $@

quiet_cmd_as_o_html = AS      $@
cmd_as_o_html = $(CC) $(a_flags) -c -o $@ \
		-DDATA_SECT_NAME="\".rodata.fsdata.$(call strip_path,$(FSPATH_$(@F)))\"" \
		-DDATA_OBJ_FILE="\"$(abspath $(srctree)/$(obj)/$(FILE_$(@F)))\"" \
		-DDATA_OBJ_NAME="fsdata_$(call strip_path,$(FSPATH_$(@F)))" \
		-DDATA_SIZE_NAME="fsdata_size_$(call strip_path,$(FSPATH_$(@F)))" \
		-DDATA_SECT_FSPATH_NAME="\".rodata.fsdata.path.$(call strip_path,$(FSPATH_$(@F)))\"" \
		-DDATA_OBJ_FSPATH_NAME="fsdata_path_$(call strip_path,$(FSPATH_$(@F)))" \
		-DDATA_OBJ_FSPATH="\"$(FSPATH_$(@F))\"" \
		-DUBOOT_LIST_SECT_NAME="\"__u_boot_list_2_fs_2_$(call strip_path,$(FSPATH_$(@F)))\"" \
		-DUBOOT_LIST_NAME="fsdata_ulist_$(call strip_path,$(FSPATH_$(@F)))" \
		$(srctree)/$(src)/embed.S

$(obj)/.min/%.html: $(src)/%.html $(WEBUI_FAILSAFE_HTML_MINIFY_SCRIPT) FORCE
	$(call cmd,force_checksrc)
	$(call if_changed,minify_html)

$(obj)/%.o: $(obj)/.min/%.html FORCE
	$(call if_changed_dep,as_o_html)

$(obj)/.min/%.css: $(src)/%.css $(WEBUI_FAILSAFE_CSS_MINIFY_SCRIPT) FORCE
	$(call cmd,force_checksrc)
	$(call if_changed,minify_css)

$(obj)/style.o: $(obj)/.min/style.css FORCE
	$(call if_changed_dep,as_o_html)

$(obj)/.min/%.js: $(src)/%.js $(WEBUI_FAILSAFE_JS_MINIFY_SCRIPT) FORCE
	$(call cmd,force_checksrc)
	$(call if_changed,minify_js)
$(obj)/%.o: $(obj)/.min/%.js FORCE
	$(call if_changed_dep,as_o_html)

$(obj)/%.o: $(src)/%.svg FORCE
	$(call cmd,force_checksrc)
	$(call if_changed_dep,as_o_html)

clean-files += .min/*
